name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:      

      - name: Docker Build and push
        run: |
          docker build -t wisecow-app.
          docker tag tic-tac-toe naresh3451213/wisecow-app:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push hakunamatata2292/tic-tac-toe:latest
        env:
          DOCKER_CLI_ACI: 1

      


